[project]
name = "langfun-notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langfun[llm,ui]>=0.0.1",
]

[tool.uv]
dev-dependencies = []
